apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
  namespace: ticketable-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: IMAGE_WILL_BE_REPLACED_BY_CD
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ticket-config
            - secretRef:
                name: ticket-secrets