apiVersion: v1
kind: Secret
metadata:
  name: ticket-secrets
  namespace: ticketable-project
type: Opaque
stringData:
  DB_URL: "${{ secrets.DB_URL }}"
  DB_USERNAME: "${{ secrets.DB_USERNAME }}"
  DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
  REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"
  JWT_SECRET_KEY: "${{ secrets.JWT_SECRET_KEY }}"
  IMPORT_API_KEY: "${{ secrets.IMPORT_API_KEY }}"
  IMPORT_API_SECRET: "${{ secrets.IMPORT_API_SECRET }}"
  ACCESS_KEY: "${{ secrets.ACCESS_KEY }}"
  SECRET_KEY: "${{ secrets.SECRET_KEY }}"