apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: ticketable-project
type: Opaque
stringData:
  JWT_SECRET_KEY: "${{ secrets.JWT_SECRET_KEY }}"
  JWT_ACCESS_TOKEN: "${{ secrets.JWT_ACCESS_TOKEN }}"
  REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"