apiVersion: v1
kind: Secret
metadata:
  name: waiting-secrets
  namespace: ticketable-project
type: Opaque
stringData:
  DB_URL: "${{ secrets.DB_URL }}"
  DB_USERNAME: "${{ secrets.DB_USERNAME }}"
  DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
  REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"