apiVersion: v1
kind: Service
metadata:
  name: waiting
  namespace: ticketable-project
spec:
  selector:
    app: waiting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP