apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: ticketable-project
data:
  SPRING_CLOUD_AWS_REGION_STATIC: "${{ secrets.REGION_VALUE }}"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  JWT_ACCESS_TOKEN: "${{ secrets.JWT_ACCESS_TOKEN }}"
  BUCKET_NAME: "${{ secrets.BUCKET_NAME }}"